name: ufly
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_search_bar: ^0.1.6
  pull_to_refresh: ^1.5.6
  get_version: 0.2.0+1
  geolocator: 5.1.3
  firebase_storage: 3.0.6
  cloud_firestore: 0.12.9+4
  shared_preferences: 0.5.3+4
  connectivity: ^0.4.5+2
  #cloud_functions: 0.4.1+1
  firebase_database: 3.1.3
  fl_chart: ^0.2.2
  firebase_remote_config: 0.2.0+7
  firebase_analytics: 5.0.2
  firebase_messaging: 5.1.8
  firebase_performance: 0.3.0+5
  firebase_auth: 0.14.0+5
  image_picker: 0.6.3+1
  firebase_core: 0.4.0+9
  #app_review: 1.0.0
  #flutter_search_panel: ^1.0.1
  location: 2.3.5
  flutter_spinkit: 4.0.0
  json_annotation: 2.2.0
  camera: 0.5.7+3
  google_sign_in: 4.0.7
  #qr_flutter: 3.0.1
  share: 0.6.2+1
  photo_view: 0.5.0
  cached_network_image: '2.0.0-rc'
  googleapis_auth: 0.2.11+1
  googleapis: ^0.54.0
  #flutter_twitter_login: ^1.1.0
  geocoder: ^0.2.1
  esys_flutter_share: ^1.0.2
  flutter_secure_storage: 3.3.1+1
  flutter_swiper: 1.1.6
  path_provider: 1.4.0
  flutter_full_pdf_viewer: ^1.0.6
  material_design_icons_flutter: 3.2.4495
  latlong: 0.6.1
  flutter_calendar_carousel: 1.3.28
  flutter_webview_plugin: 0.3.8
  flutter_slidable: 0.5.3
  timeago: 2.0.20
  flutter_masked_text: 0.8.0
  flutter_typeahead: 1.6.1
  flutter_range_slider: ^1.4.0
  flutter_auth_buttons: 0.5.0
  flare_checkbox: ^1.0.2
  flutter_share_me: ^0.6.0
  progress_dialog: ^1.2.0
  permission: ^0.1.3
  share_extend: ^1.0.9
  flutter_local_notifications: 0.8.3
  #quiver: 2.0.5
  flip_panel: 1.0.0
  launch_review: 2.0.0
  #google_maps_flutter_heatmap: 0.1.1+2
  fluttertoast: 3.1.3
  quick_actions: ^0.3.2+2
  screenshot: ^0.1.1
  autocomplete_textfield: ^1.7.3

  #flutter_duration_picker: 1.0.4
  date_range_picker: 1.0.6
  expandable: 4.1.2
  random_color: 1.0.3
  #super_tooltip: ^0.9.0
  #true_time: ^0.1.0
  font_awesome_flutter: 8.5.0
  #uuid: 2.0.1
  shimmer: 1.0.1
  url_launcher: 5.1.4
  sqflite: 1.1.6+5
  #intro_views_flutter: ^2.8.0
  image_crop: ^0.3.1
  flutter_charts: ^0.1.10
  #flutter_cielo: ^1.0.7
  flare_flutter: ^1.5.9
  flutter_cupertino_date_picker: 1.0.12
  geohash: ^0.2.1
  datetime_picker_formfield: 0.4.3
  random_string: ^1.1.0
  #qrcode_reader: ^0.4.4
  
  in_app_purchase: ^0.2.1+4
  #streamqflite: ^1.0.0
  bloc_pattern: ^1.5.2
  google_fonts: 0.7.0
  rxdart: ^0.22.0
  flutter_staggered_grid_view: 0.3.0
  #redux: 3.0.0
  #syncfusion_flutter_charts: ^1.0.0-beta.1
  redux_logging: 0.3.0
  dio: 3.0.2
  flutter_foreground_plugin: any
  pdf: ^1.3.24
  csv: ^4.0.3
  device_info: 0.4.1+1
  wakelock: ^0.1.4+2
  cpf_cnpj_validator: ^1.0.5
  line_awesome_icons: ^1.0.4+2
  image: ^2.1.4
  cupertino_icons: ^0.1.2
  flutter_screenutil: 0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Malgun
      fonts:
        - asset: fonts/malgun.ttf
    - family: BankGothic
      fonts:
        - asset: fonts/BankGothic.ttf

  assets:
    - assets/
